Jaishree2310/GlassyUI-Components

- src/App.tsx
- src/components/NotFoundPage.tsx
- Created a NotFoundPage component to handle 404 errors.
- Implemented a stylish glassmorphic design for the 404 page.
- Updated the App component to include routing for the NotFoundPage.
- Ensured responsiveness for mobile, iPad, and desktop devices.
- Added a button on the 404 page to navigate back to the home page.
> Add 404 Not Found Page and Update Routing

- src/App.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Tooltip.tsx
- src/components/TooltipDetailsPage.tsx
Introducing a new Tooltip component to the GlassyUI library, implementing a glassmorphism theme.
- Displays helpful information on hover
- Customizable text content
- Multiple position options (top, bottom, left, right)
- Glassmorphism styling (transparency, blur effect, frosted glass look)
- Responsive design
1. `GlassyUIComponentsPage.tsx`
2. `App.tsx`
3. `TooltipDetailsPage.tsx`
4. `Tooltip.tsx` 
(Screenshot : 1)
(Screenshot : 2)
- [+] Component code implemented
- [+] Styling adheres to glassmorphism theme
- [+] Responsive design tested
- [+] Code follows project style guidelines
- [+] Support different positions (top, bottom, left, right).
> #9  Add : Glassmorphic Tooltip Component to GlassyUI

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature.yml
Hello:)
I have added the github issues templates
closes #15
> Feat: Github Template issues

- src/components/BackToTop.tsx
- src/components/ButtonDetailsPage.tsx
- src/components/CardDetailsPage.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/InputDetailPage.tsx
- src/components/PopupDetailPage.tsx
- src/components/ProgressBarDetailPage.tsx
- src/components/SpeedDialDetailsPage.tsx
- src/components/TextareaDetailPage.tsx
- src/components/TooltipDetailsPage.tsx
https://github.com/user-attachments/assets/56827038-2605-4da7-b4f4-d23c4d12154c
> Made the bottom to top button

- src/components/ButtonDetailsPage.tsx
- src/components/CardDetailsPage.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/GlassyUILandingPage.tsx
- src/components/InputDetailPage.tsx
- src/components/ModalDetailsPage.tsx
- src/components/NotFoundPage.tsx
- src/components/ProgressBarDetailPage.tsx
- src/components/SpeedDial.tsx
- src/components/SpeedDialDetailsPage.tsx
- src/components/TextareaDetailPage.tsx
- src/components/TooltipDetailsPage.tsx
close #55 
I have enhance the quality of color combination now website look more beautiful and Clear and clean user experience 
clean color contract 
clear visiualization of text 
Before this PR
After this PR
This PR make the website even more eligant
> enhance color combinatin #55

- README.md
Fixes: #34 
Changes Made:
1. Updated the README to provide a more engaging and comprehensive overview of the GlassyUI-Components library.
2. Added a detailed section on usage and contribution guidelines to facilitate easier onboarding for new contributors.
3. Included images from the website for better visualization of the components and their effects.
These enhancements aim to improve the clarity and usability of the project documentation. Kindly Merge my PR. 
Thank you @Jaishree2310 :)
> Enhanced README for GlassyUI-Components

- src/components/SpeedDialDetailsPage.tsx
fixes #66 
Now it is opening in right direction
> fix button ui issue

- .eslintignore
- .husky/pre-commit
- .prettierignore
- .prettierrc
- eslint.config.mjs
- package-lock.json
- package.json
Added husky pre commit lint staged 
closes issue #23
> created Husky setup

- src/components/GlassyUIComponentsPage.tsx
- src/components/SpeedDialDetailsPage.tsx
This pull request introduces an update to the Twitter logo in the `GlassyUIComponentsPage.tsx` file, along with modifications in the `SpeedDialDetailsPage.tsx` file. The changes enhance the visual consistency and modernize the user interface.
- Updated the Twitter logo in `src/components/GlassyUIComponentsPage.tsx`
- Modified relevant components in `src/components/SpeedDialDetailsPage.tsx` to ensure compatibility with the new logo.
This update aims to improve the user experience by providing a more contemporary and recognizable Twitter logo. It is part of our ongoing efforts to keep the UI fresh and aligned with current design trends.
- Closes [#71](https://github.com/Jaishree2310/GlassyUI-Components/issues/71)
Thank you for reviewing this pull request!
> Update Twitter logo 

- src/App.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/SliderDetailsPage.tsx
https://github.com/user-attachments/assets/f98a419f-51fc-490a-a2a8-8d57ea5f945c
> Issue 50 add slider component to glassy UI

- src/App.tsx
- src/components/DonationPage.tsx
- src/components/Header.tsx
This pull request adds a new donation feature to the application, allowing users to contribute financially to website maintainers. It includes a new **DonationPage** and **Header** (for containing the Donate button)  **component** where users can enter their donation amount and their details.
Closes #90 (Add donation functionality)
1. Navigate to the `/donate` route.
2. Fill in the donation form with various amounts to verify validation.
**Before:**
**After:**
> Donation Page added 

- src/components/GlassyUIComponentsPage.tsx
aligned learn more and arrow icon
> aligned arrow icon

- src/App.tsx
- src/components/AuthenticationCards.tsx
- src/components/GlassyUIComponentsPage.tsx
Fixes #70 
I have added the Authentication cards components to the website
@Jaishree2310  Please merge this Pull Request with the labels attached
> Glassy Authentication Cards Added Issue no #70 Resolved

- package-lock.json
- package.json
- src/components/GlassyUILandingPage.css
- src/components/GlassyUILandingPage.tsx
- src/styled-jsx.d.ts
#85 done added everything working perfectly 
https://github.com/user-attachments/assets/4482514a-143f-42ea-a532-1fd257606f3e
can you add gsoc ext Level 2 or 3 to this at least
> Change the Hero section and added animations and transitions

- src/App.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Toast.tsx
- src/components/ToastGenerator.tsx
- src/components/ToastPage.tsx
- src/index.css
Fixes #67 
this implements a glassy-themed toast component to enhance user notifications with a modern and elegant design.
> Fixes: #67: NEW TOAST COMPONENT

- src/components/NavigationDetailsPage.tsx
Fixes #103 
I have fixed Navigation Bug @Jaishree2310 , Please Check . 
Now the "Back to Components" is working according to the description.
[GlassyUI - Google Chrome 2024-10-12 16-22-59.zip](https://github.com/user-attachments/files/17349759/GlassyUI.-.Google.Chrome.2024-10-12.16-22-59.zip)
> Navigation Bug Fixed 

- src/App.tsx
- src/components/DropdowndetailsPage.tsx
- src/components/GlassyUIComponentsPage.tsx
issue #81 
created drop down menu
> added dropdown menu component

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
I have Added the docker for this project.
fix: #109
> added the docker

- package-lock.json
- package.json
- src/App.tsx
- src/components/Accordion.tsx
- src/components/AccordionDetails.tsx
- src/components/GlassyUIComponentsPage.tsx
This pull request adds a new Accordion component and integrates it into the app. Key updates include:
Accordion Component: A new Accordion.tsx with glassmorphic styling and toggle functionality.
Accordion Details Page: A detailed AccordionDetails.tsx page showcasing basic and collapsible accordions, plus code examples with copy-to-clipboard.
Integration:
Updated App.tsx to include a route for the AccordionDetails page.
Updated GlassyUIComponentsPage.tsx to display the Accordion component with sample content.
> Added Accordion component issue #116

- package-lock.json
- src/App.tsx
- src/components/AboutUsPage.tsx
- src/components/Header.tsx
This pull request introduces a revamped **About Us** page for the **GlassyUI-Components** project. The enhancements include updated content that emphasizes our community-driven mission and the value we provide to developers, designers, and contributors. Additionally, the styling has been refined to improve readability and visual appeal.
issue #91 solved
> Added AboutUs Page

- src/App.tsx
- src/components/BackToTopDetailsPage.tsx
- src/components/GlassyUIComponentsPage.tsx
issue #80 
Provided code for it 
example of code
> Added back to top button

- package-lock.json
- package.json
- src/components/GlassyUILandingPage.tsx
- src/components/Header.tsx
fixes #117 
demo 
https://github.com/user-attachments/assets/52f6c977-3622-4105-b36b-8fca3edf6dbb
> added gsap animation to homepage fixes #117

- src/App.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/PricingDetailPage.tsx
issue #79 
Done pricing page 
added code for pricing page components
also given prop for it 
and given some example
> Added pricing page component

- README.md
- Updated the website preview screenshot in the README file to accurately represent the current UI.
- Ensured the preview reflects the recent design improvements, providing a more up-to-date view for users browsing the repository.
- This change enhances the clarity and consistency of the project documentation.
> Update website preview section in README file to reflect new UI changes

- package-lock.json
- package.json
- src/components/AboutUsPage.tsx
- src/components/DonationPage.tsx
- src/components/GlassyUIComponentsPage.tsx
I have added the input validations and improved the UI of about page
Pls check
> improve ui and validation added

- README.md
> Added photos of all contributors fixes #133

- package-lock.json
- package.json
- src/App.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/SearchbarDetails.tsx
fixes #136 
Added the searhbar card in GlassyUIComponents page and Searchbar component on the /searchbar-details route .
https://github.com/user-attachments/assets/a01c8fdb-5f6d-4252-bf4d-03bb4ed29092
> Add Searchbar Component

- src/components/GlassMorphismGenrator.tsx
- src/components/GlassyUIComponentsPage.tsx
Closes #153 
Fix Glassmorphism Visibility and Add Glassmorphism Generator to Component Page
**Description**
This pull request addresses the visibility issues in the glassmorphism preview block and integrates a glassmorphism generator into the component page. The updates enhance the user experience by ensuring that the glassmorphism effect is properly displayed and customizable.
**ScreenShot:-**
**Changes Made**:-
> Fix visibility issue in glassmorphism generator component

- README.md
**Closes : #150**
To address the issue of transparency regarding updates and changes in the GlassyUI-Components library, I propose adding a Changelog section to the project’s README file. This changelog will systematically document all notable changes, including new features, enhancements, bug fixes, and any breaking changes, using a clear and organized format. By following semantic versioning (MAJOR.MINOR.PATCH), users can easily grasp the significance of updates. Each entry will include the date of the change, along with specific sections for added features, modifications to existing functionalities, and resolved issues. Including a section for unreleased changes will also help users anticipate future improvements. Drawing inspiration from successful implementations like the changelogs …
> ADDING a CHANGELOG Section in README file

- src/App.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/PaginationDetails.tsx
issue #120 
https://github.com/user-attachments/assets/447288fc-27c8-4a50-9a23-8ae111151e99
Added fully customizable pagination components 
We can set everything manually 
provided the logical and UI part of pagination 
also Console the current page for better integration 
We can setup everything manually more control to user
Kind request Can i get level 3 for it as it required lot of effort to put that logic !
> Added pagination

- src/components/GlassyUIComponentsPage.tsx
- src/components/ProgressBarDetailPage.tsx
#82 
Before merging this PR
After merging this PR
> fixed progress bar width in mobile view

- README.md
Closes: #148 
By adding a roadmap section to the README, we can:
Provide visibility into planned features and enhancements, fostering excitement and anticipation within the community.
Encourage contributions by outlining specific areas where help is needed, making it easier for users to get involved.
Establish a clear direction for the project, demonstrating a commitment to continuous improvement and engagement with the user base.
This addition will ultimately strengthen the GlassyUI-Components library and create a more collaborative environment for developers and users alike.
> ADDING ROADMAP IN README

- src/components/AccordionDetails.tsx
- src/components/AuthenticationCards.tsx
- src/components/BackToTopDetailsPage.tsx
- src/components/ButtonDetailsPage.tsx
- src/components/DropdowndetailsPage.tsx
- src/components/GlassMorphismGenrator.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/InputDetailPage.tsx
- src/components/ModalDetailsPage.tsx
- src/components/NavigationDetailsPage.tsx
- src/components/PaginationDetails.tsx
- src/components/PopupDetailPage.tsx
- src/components/PricingDetailPage.tsx
- src/components/ProgressBarDetailPage.tsx
- src/components/SliderDetailsPage.tsx
- src/components/SpeedDialDetailsPage.tsx
- src/components/TestimonialDetails.tsx
- src/components/TextareaDetailPage.tsx
- src/components/ToastPage.tsx
- src/components/TooltipDetailsPage.tsx
To bring uniformity in all components pages in terms of structure:
All the changes done (along with solving few bugs on the way):
- Same title size/color and other styles in UI for all components
- same table format for all component pages
- Fixed Input component where text in `border-width` and `border-radius` were white and not visible
ORIGINAL
AFTER MY CHANGE
- Navigation and Pop-ups Page background was still pink, made it dark like other components, and also adjusted the text color as other components
AFTER MY CHANGE 
- TextArea Page background was fully white made it dark themed like other components
AFTER MY CHANGE
- Added `import { HiOutlineWrenchScrewdriver } from 'react-icons/hi2';` in GlassyUiComponents.tsx which was probably deleted in prev merges, which threw error while …
> Fix table and title format across all the components to maintain uniformity

- src/components/GlassyUIComponentsPage.tsx
I have added the search functionality
https://github.com/user-attachments/assets/ecd28413-639b-450a-9eea-1d380ffc82cb
fix: #88
> added search functionality

- README.md
fix: #177 
Updated with correct domain
> updated readme with correct demo link 

- src/components/CardDetailsPage.tsx
Fix: #162 
Changed class from *text-gray-900* to **text-white**
> improve card page title visibilty

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Footer.tsx
- src/components/GlassyUIComponentsPage.tsx
Added a footer with quicks links to different components. @Jaishree2310 please merge the PR accordingly.
> solved issue #78

- package-lock.json
- src/components/ContributorsPage.tsx
- src/components/GlassyUIComponentsPage.tsx
This pull request adds a "Scroll Down" button to the Components page and the Contributors page of the project, enhancing user navigation experience. When clicked, the button smoothly scrolls the page to the next section, allowing users to easily explore the content below. This feature is helpful when the application is used in different screen sizes.
Issue No: #128 
* Updated src\components\GlassyUIComponentsPage.tsx
* Updated src\components\ContributorsPage.tsx
Thank you :)
> added-scroll-down-button

- src/components/DonationPage.tsx
I have changed the UI of donation page pls check
> changed donation page ui

- src/components/Header.tsx
fixes issue #159 
Changed the CSS of nav class to stay sticky on top. 
Here is the screenshot for reference.
> Fixed navbar with the blur background

- package-lock.json
- package.json
- src/components/ContributorsPage.tsx
Fixes #174 
I have fixed the pagination issue of contributors API and developed a solution that fetches entire data of contributors to the repo.
> Fixed Contributors Data bug

- package-lock.json
- src/components/AboutUsPage.tsx
- src/components/BackToTop.tsx
- src/components/ContributorsPage.tsx
I have added the scroll to top button in about and contributors page
pls check
> added scroll to top button

- src/components/Footer.tsx
- src/components/GoogleTranslator.jsx
issue #223 
https://github.com/user-attachments/assets/e950a909-1f51-4cdf-b9a4-51fb43239ac3
in video its not showing options block but when you click on select language it will show you many option as shown in SS
> Google translator added

- src/components/ContributorsPage.tsx
I have added paging support in contributors page pls check
> add paging in contributor page

- package-lock.json
- package.json
- src/App.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/ScrollProgress.tsx
@Jaishree2310 
I have created scroll progress bar successfully
Kindly look at it
https://github.com/user-attachments/assets/5eaa8fc8-fc73-4171-a6d3-7091f51c40ed
> added scroll progress bar

- src/index.css
hey @Jaishree2310 ,
issue closes #189.
i have updated the vertical scrollbar and add transition to it .
can you please merge it ?
> Updated the vertical scrollbar

- public/index.html
This PR updates the meta tags in the index.html file to improve the SEO and social sharing capabilities of the GlassyUI website. 
**The changes include:**
- Revised meta title and description with targeted keywords for better search engine visibility.
- Added keywords meta tag to boost search relevance for UI design and React components.
- Implemented Open Graph and Twitter meta tags to enhance how the site is displayed when shared on social media platforms.
- Ensured the existing structure remains intact while optimizing the meta content.
- Improves website visibility in search engine results.
- Enhances the presentation when sharing on social media platforms like Facebook and Twitter.
fixes: #259 
Kindly merge it @Jaishree2310 and do let me know if any queries are there related to it!!
> Update Meta Tags for Improved SEO and Social Sharing

- src/App.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/StatisticDetails.tsx
issue #221 
https://github.com/user-attachments/assets/2ac326e7-41f1-42a9-b816-0243c1d0f51e
> Feat statictis component

- src/components/CardDetailsPage.tsx
I have fixed the text color issue in Card Component
Issue #236
> Text color issue fixed

- src/components/Header.tsx
Fixes #172  #210 Edit navbar and make it better from previous one.
@Jaishree2310 Please review my PR and merge it:)
> BUG: Edit Navbar and make it good

- src/components/DonationPage.tsx
I have added glassmorphism theme in donation page
Issue #303
> Added glassmorphism theme in donate page

- README.md
**Closes** : #335 
**Description**
The README currently does not include a "Contact Us" button in the footer, which makes it difficult for users to quickly find contact information.
**Issue Reference** : #335 
**Screenshot** :
> ADD "Contact Us" Button on the Footer of the README 

- src/components/AboutUsPage.tsx
the overlapping has been resolved
resolves issue #317 
@Jaishree2310  kindly review and merge my pr
> Update AboutUsPage. #317

- src/App.css
- src/index.css
@Jaishree2310 added code to css files to ensure viewport width is fixes to 100% #325
> fixes #325: width for mobile view

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/documentaion.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/pullrequest_template.md
- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/ContributorsPage.tsx
- src/components/DonationPage.tsx
- src/components/Footer.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
Closes : #370 
- I have enhanced the GitHub issue template by adding distinct sections for features, bug fixes, and documentation updates. 
This provides contributors with clear guidance on how to categorize their contributions, ensuring better organization and 
clarity in project management.
- The pull request template has also been refined to align with the new issue structure. This includes prompts for contributors 
to summarize their changes effectively, highlight major enhancements, and confirm adherence to project guidelines.
- These modifications streamline the contribution process, making it easier for maintainers to review submissions and for 
contributors to present their work comprehensively. This ultimately enhances collaboration and the overall quality of the 
project.
> Changed all  the ISSUE TEMPLATES and Pull request template !!!

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/ThemeTogggle.tsx
> Added chatbot !!!

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
https://github.com/user-attachments/assets/e2148f08-11e8-4bb8-9937-d495c6540544
> Added Animated Icons in the navbar !!!

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
> Enhancing the SearchBar and added Search icon for user experience !!

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
This pull request introduces a visually appealing custom scrollbar to improve the overall user experience of the application. The following changes have been made:
- **Custom Scrollbar Styles:** Implemented a custom scrollbar that aligns with the application's aesthetic, enhancing the glassmorphism design.
- **Cross-Browser Compatibility:** Ensured the scrollbar styles are compatible with major browsers, including Chrome, Firefox, and Edge.
- **Responsive Design:** Adjusted scrollbar dimensions and colors for various screen sizes to maintain usability and accessibility.
- Updated the CSS to include custom scrollbar styles using `::-webkit-scrollbar` for Chrome and Safari.
- Added fallback styles for Firefox and other browsers.
- Tested functionality across different devices and browsers …
> Imrproved the UI of Scrollbar

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/DonationPage.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
https://github.com/user-attachments/assets/249bc9e0-1de1-402d-84c4-94073b9de90f
This repository features a Donation Page component built using React and TypeScript. The component includes:
- **User-Friendly Donation Form**: Collects user input for donation amount, name, and email, with real-time validation using the `zod` library.
- **Responsive Design**: Utilizes modern CSS styling for a clean and engaging user interface.
- **State Management**: Implements React hooks to manage form state and submission status.
- **Navigation**: Uses the `useNavigate` hook from `react-router-dom` to navigate back to the home page after a successful donation.
- **Error Handling**: Displays error messages for invalid input, ensuring a smooth user experience.
This project demonstrates how to create a …
> Donation Page Component with Form Validation and Navigation

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/DonationPage.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
Elevate your web application’s user experience with our newly integrated smooth cursor feature. Designed with a gradient of captivating blue shades, this cursor not only enhances interactivity but also adds a modern aesthetic to your interface. The seamless transitions and refined look ensure that users enjoy a visually appealing and engaging browsing experience. Perfect for developers looking to incorporate stylish and functional design elements into their projects.
https://github.com/user-attachments/assets/89c37c4c-195f-4f9b-b0a8-db29960ee492
> Enhanced User Experience with a Smooth Cursor

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/DonationPage.tsx
- src/components/Footer.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
This update enhances the footer section, providing a polished and user-friendly experience. Key features include:
- **Structured Layout**: The footer is divided into clearly defined sections, making it easy for users to navigate to components, contributors, donations, and the about page.
- **Social Media Links**: New social media icons for Twitter/X, Facebook, LinkedIn, and Instagram allow users to connect with us on multiple platforms. Each icon is clickable and directs to the corresponding profile.
- **Hover Effects**: Smooth hover animations for both links and icons, adding interactivity and a modern touch to the footer.
- **Copyright Information**: Includes an up-to-date copyright notice to reflect the current year, enhancing professionalism.
These changes bring consistency and style, …
>  Refactor Footer Component to Enhance Structure and Responsiveness

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/DonationPage.tsx
- src/components/Footer.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
- Closes:- #352
This pull request introduces hover effects to the card components on the `GlassyUIComponentsPage`. The enhancements improve user interaction by providing visual feedback when users hover over the cards, making the interface more engaging and intuitive.
- Added CSS hover effects to the following card components:
- **Like Button Card**: Enlarges the card and changes the background color on hover.
- **Contact Card**: Slightly lifts the card and applies a subtle shadow effect.
- **Accordion Card**: Changes the border color and increases the scale on hover.
- **Additional Cards**: Similar hover effects applied across all card components for consistency.
- Modified the CSS file associated with the card components to include hover styles.
- Updated the card component JSX to …
> Enhance Card Components with Hover Effects

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/Checkbox.tsx
- src/components/ContributorsPage.tsx
- src/components/DonationPage.tsx
- src/components/Footer.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/Header.tsx
- src/components/ThemeTogggle.tsx
"This PR adds a prominent 'Become a Contributor' button to the interface, designed to encourage user engagement and contributions. The button features an improved UI with a gradient background, rounded corners, and smooth hover effects for a modern look. Additionally, the URL paths have been verified and corrected to ensure seamless navigation to the GitHub repository.
Introduced a new button style with gradient colors and smooth hover transitions
Adjusted alignment and padding for better visual appeal
Corrected URL paths to ensure accurate redirection
> Added 'Become a Contributor' Button with Enhanced UI and Corrected URL Paths

- PROJECT_STRUCTURE.md
- repo_structure.txt
updated the repo structure in repo_structure.txt and PROJECT_STRUCTURE.md
> Update repo structure

- src/components/Footer.tsx
issue #343 
fixed the bugs  &  enhances the footer
@Jaishree2310 ma'am pls see this pr I ve close the old pr & create the new pr (issue #343 )
pls merge this asap !!
> enhanced the footer now well organised 

- package-lock.json
- package.json
- src/components/Header.tsx
**Fixed Navbar Styling:** I corrected the CSS styles in the Header component for improved alignment, spacing, and dark mode compatibility.
**Enhanced Responsive Layout:** Adjusted layout styles to ensure a consistent display across different screen sizes.
> Navbar fixed

- src/App.tsx
- src/components/Footer.tsx
- src/components/GlassyUIComponentsPage.tsx
- src/components/ModalDetailsPage.tsx
- src/components/SpeedDialDetailsPage.tsx
https://github.com/user-attachments/assets/29ee314e-0bb1-4427-9d6c-a378fed4bc20
i have remove all the issue but then too it is showing some unexpected error
page is not rendering properly and components doesn't get scroll
i also have older version of glassui 
if you want i can make PR of that tooo
> Removed all issues

- src/App.tsx
- src/components/Footer.tsx
- src/components/TermsOfUse.tsx
https://github.com/user-attachments/assets/fa7f7f75-8fcb-46cc-9d3b-67b7790bb085
Added terms of use 
This PR introduces a new "Terms of Use" page to the application, outlining the terms and conditions that govern the use of our services. The document includes various sections that define user obligations, intellectual property rights, limitation of liability, dispute resolution, and more, providing a comprehensive legal framework for users.
Changes Made
Created a new page named TermsOfUse.
Structured the content into relevant sections for clarity:
Acceptance of Terms
User Obligations
Intellectual Property Rights
Limitation of Liability
Indemnification
Termination Clause
Governing Law
Modification of Terms
Legal Compliance
Dispute Resolution
> Added terms of use for glassy UI 🚀✨

- src/App.tsx
- src/components/Footer.tsx
Before there are 2 footer 
Bad Ui / Ux
After
> fixes the 2 footer issues

- src/App.tsx
- src/components/AIChatbot.tsx
- src/components/BackToTop.tsx
issue : #426
https://github.com/user-attachments/assets/6b0531e6-5bbf-4cd9-b653-76194dea21ed
> Added ai supported chatbot

- server/.env.example
- server/.gitignore
- server/app.js
- server/controllers/contactController.js
- server/model/contact.js
- server/package.json
- server/routes/contactRoutes.js
- server/utils/db.js
- server/utils/sendMail.js
- src/App.tsx
- src/components/ContactUs.tsx
- src/components/Header.tsx
issue : #405 
https://github.com/user-attachments/assets/02a65e79-11a8-4106-9128-e39d5c6836fb
i have added send mail feature to contact form for instant resolving the user querry
in the formated way you will get mail to your mail account
clean and clear UI of mail
fill this env.example info for using this mail feature
admin mail where you want to send the user info
mail by this mail you will receive mail
passkey you have to generate one from
application password on mail !!
> Implemented contact form with frontend and Backend API

- package-lock.json
- package.json
- src/App.tsx
- src/components/Header.tsx
- src/index.tsx
- src/login/SignIn.tsx
- src/login/SignUp.tsx
- src/login/UserAccount.tsx
- src/login/contexts/authContext/index.tsx
- src/login/firebase/auth.js
- src/login/firebase/firebase.js
https://github.com/user-attachments/assets/5a1a1537-c3c7-4de2-a1ea-5b84f6005fc9
also handle errors
you can signup by your email and password too
if you need some changes i can do it 
Dependency used : firebase
> ✨ Added signup signin feature by google ✨

- server/app.js
- server/controllers/newsletterController.js
- server/model/Newsletter.js
- server/routes/newsletterRoute.js
- server/sendSuscribedMail.js
- src/components/Footer.tsx
https://github.com/user-attachments/assets/d9f2905e-fc88-4a27-b6a3-6af20484a30f
This PR introduces the "Subscribe Us" feature to the backend, enabling users to subscribe to the platform by submitting their name and email
Once subscribed, users receive a welcome email with details about the platform and its offerings.
Also saved the details of the user in the database for future !!
> ✨ Added newsletter functionality to glassy ui ✨

- public/index.html
- server/app.js
- server/controllers/postsController.js
- server/model/postModel.js
- server/routes/storiesRoutes.js
- src/App.tsx
- src/components/Header.tsx
- src/components/Stories.tsx
This PR introduces a new Story page 
The page layout is optimized to showcase user stories with a visually engaging,  
Key features include an intuitive interface, support for multimedia content, and easy navigation for readers.
This addition enhances the user experience by providing a dedicated space for storytelling, allowing bloggers to share content in a more engaging format
This PR implements the backend for the Stories page, including the following:
GET /api/posts: Fetches all the stories (posts) from the database.
POST /api/posts: Allows users to create and save new stories by submitting title, content, and category data.
The data is stored in a MongoDB database using Mongoose, and the backend handles both the creation and retrieval of posts.
Changes include:
Creation of routes and …
> Build frontend and Backend for Stories Page: Implement POST and GET Routes | clean schema✨🚀

- src/components/Footer.tsx
**Description**
This PR fixes #448 
- Replaced the boxed footer section with a horizontal line for a cleaner separation from the main content.  
- Simplified and refactored the layout to ensure better readability and maintainability.  
- Maintained functionality for newsletter subscription and external GitHub link.  
- Applied minimal inline styles and transitioned to class-based styles for consistency.  
- Addressed potential issues such as lack of validation and improved focus states for input fields.  
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
**Preview**
---
> updating footer section

- InputField.css
**Description**
This pull request adds comprehensive unit tests for the Input Field component to ensure both functionality and glassmorphism styles are implemented correctly. The tests validate various input scenarios, including:
1. Support for multiple input types (text, email, password, etc.).
2. Handling of value changes and event triggers (onChange, onBlur, onFocus).
3. Verification of the glassmorphism styles, such as transparency, blur effects, and border styles.
The tests are written using Jest and React Testing Library. All scenarios are covered to ensure the component meets design and functionality expectations, and all tests pass successfully.
>  Write Unit Tests for Input Field Component with Glassmorphism Validation
